

name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: oven-sh/setup-bun@v2
      - run: bunx npm config set -- '//registry.npmjs.org/:_authToken' "${NPM_AUTH_TOKEN}"
      - run: bun install
      - run: bun run build
      - run: bun publish --provenance --access public
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
